import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import FontProvider from "./fontProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <link
          href={`https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined`}
          rel="stylesheet"
        />
      </head>
      <body>
        <Providers>
          <FontProvider>{children}</FontProvider>
        </Providers>
      </body>
    </html>
  );
}
